import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{var s=localStorage.getItem('modern-builder-v1');var d=true;if(s){var o=JSON.parse(s);if(Object.prototype.hasOwnProperty.call(o,'dark')){d=!!o.dark;}}var el=document.documentElement;el.classList.toggle('dark', !!d);}catch(e){}})();",
          }}
        />
        {children}
      </body>
    </html>
  );
}
